export const INCREMENT = 'increment'
export const DECREMENT = 'decrement'
export const ADD_PERSON = 'addPerson'
export const SET_BANNER = 'setBanner'
export const SET_RECOMMEND = 'setRecommend'
export const SET_SAGA_BANNER = 'setSagaBanner'
export const SET_SAGA_RECOMMEND = 'setSagaRecommend'
export const FETCH_SAGA_INFO = 'fetchSagaInfo'
